package com.epam.hackme.common;

public interface HackMeConstants {
String SUCCESS="success";
String NOT_SUCCESS="nosuccess";
String USERNAME="username";
String PASSWORD="password";
String ADMIN="admin";
String PLAIN_COOKIE="alex";
String PLAIN_COOKIE_VALUE="alex1";
String ENCRYPTED_COOKIE_PASSWORD_KEY="enCkepwd";
String ENCRYPTED_COOKIE_PASSWORD_VALUE="hello";
String ENCRYPTED_SOURCE_CODE_PASSWORD_KEY="ensrcpwd";
String ENCRYPTED_SOURCE_CODE_PASSWORD_VALUE="welcome";
String CHALLENGE_ZERO="/challengelogin";
String VALIDATE_CHALLENGE_ZERO="validatechallenge0";
String CHALLENGE_TWO="/challenge2";
String VALIDATE_CHALLENGE_TWO="/validatechallenge2";
String CHALLENGE_THREE="/challenge3";
String VALIDATE_CHALLENGE_THREE="/validatechallenge3";
String CHALLENGE_FOUR="/challenge4";
String VALIDATE_CHALLENGE_FOUR="/validatechallenge4";
String CHALLENGE_FIVE="";
String VALIDATE_CHALLENGE_FIVE="/validatechallenge5";
String CHALLENG_5_PASSWORD="Awesome";
String CHALLENG_8_PASSWORD="textpwd";
String CHALLENGE_SIX="";
String VALIDATE_CHALLENGE_SIX="/validatechallenge6";
String CHALLENGE_SEVEN="";
String VALIDATE_CHALLENGE_SEVEN="/validatechallenge7";
String CHALLENGE_EIGHT="";
String VALIDATE_CHALLENGE_EIGHT="/validatechallenge8";
String CHALLENGE_NINE="";
String VALIDATE_CHALLENGE_NINE="/validatechallenge9";
String CHALLENGE_TEN="/challenge10";
String VALIDATE_CHALLENGE_TEN="/validatechallenge10";
String CHALLANGE_10_PASSWORD="robot";
String CHALLENGE_ZERO_VIEW="challengelogin";
String CHALLENGE_ALL_VIEW="hackall";
String USER_ROLE="user";
String ADMIN_ROLE="admin";
String ROLE_TYPE="role_type";
String INVALID_URL="Invalid URL";
}
