package com.epam.hackme.common;

public interface QueryConstants {
String GET_USER_ID="SELECT USER_ID FROM EPAM_USER where USER_NAME='";
String REGISTER_USER="INSERT INTO CHALLENGE_USER VALUES(?,?,?,?)";
String IS_VALID_USER="SELECT COUNT(*) FROM CHALLENGE_USER WHERE USER_ID=? AND PASSWORD=?";
String USER_EXISTS="SELECT COUNT(*) FROM CHALLENGE_USER WHERE USER_ID=?";
String UPDATE_SCORE_IN_FIRST_CHALLENGE="UPDATE CHALLENGE_USER_SCORE SET START_TIME=SYSDATE,END_TIME=SYSDATE WHERE USER_ID=?";
String ADD_SCORE="INSERT INTO CHALLENGE_USER_SCORE VALUES(?,0,SYSDATE,SYSDATE,?,0)";
String UPDATE_SCORE="UPDATE CHALLENGE_USER_SCORE SET SCORE=(SELECT SCORE FROM CHALLENGE_SCORE WHERE CHALLENGE=?)+(SELECT SCORE FROM CHALLENGE_USER_SCORE WHERE USER_ID=?),END_TIME=SYSDATE,CHALLENGE=(SELECT CHALLENGE FROM CHALLENGE_USER_SCORE WHERE USER_ID=?)+1 WHERE USER_ID=?";
String GET_SCORE="SELECT USER_ID,USER_NAME,SCORE FROM CHALLENGE_USER_SCORE ORDER BY SCORE DESC,END_TIME-START_TIME ASC ";
String GET_My_SCORE="SELECT USER_ID,USER_NAME,SCORE,CHALLENGE FROM CHALLENGE_USER_SCORE WHERE USER_ID=?";
String UPDATE_SCORE_TRIVIAL="UPDATE CHALLENGE_USER_SCORE SET SCORE=?,START_TIME=SYSDATE,END_TIME=SYSDATE WHERE USER_ID=?";
String GET_TRIVIA_CHALLENGES="SELECT * FROM TRIVIAL_CHALLENGE_SCORE WHERE USER_ID=?";
String UPDATE_TRIVIA_ONE="UPDATE TRIVIAL_CHALLENGE_SCORE SET CHALLENGE1='Y' WHERE USER_ID=?";
String UPDATE_TRIVIA_TwO="UPDATE TRIVIAL_CHALLENGE_SCORE SET CHALLENGE2='Y' WHERE USER_ID=?";
String UPDATE_TRIVIA_THREE="UPDATE TRIVIAL_CHALLENGE_SCORE SET CHALLENGE3='Y' WHERE USER_ID=?";
String UPDATE_TRIVIA_FOUR="UPDATE TRIVIAL_CHALLENGE_SCORE SET CHALLENGE4='Y' WHERE USER_ID=?";
String UPDATE_TRIVIA_FIVE="UPDATE TRIVIAL_CHALLENGE_SCORE SET CHALLENGE5='Y' WHERE USER_ID=?";
}
